apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: akash-shopnow
spec:
  clusterIP: None        # headless — gives us the mongo-0.mongo.akash-shopnow... DNS name
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
